# Generated by Django 5.2.10 on 2026-02-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0002_add_query_optimization_indexes"),
        ("ingest", "0002_alter_eventschema_options_and_more"),
    ]

    operations = []
