# Generated by Django 5.2.10 on 2026-02-23 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ingest",
            "0004_remove_contractevent_ingest_cont_contrac_idx_timestamp_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="webhooksubscription",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("suspended", "Suspended")],
                db_index=True,
                default="active",
                help_text="Lifecycle state: active dispatches events; suspended has exhausted all retries",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="webhooksubscription",
            name="secret",
            field=models.CharField(
                help_text="HMAC secret — stored as a hex token, never logged or exposed via API",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="WebhookDeliveryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="1-based attempt counter (1 = first try, 2 = first retry, …)",
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True,
                        help_text="HTTP status code returned by the subscriber, or null for network errors",
                        null=True,
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when subscriber returned a 2xx response",
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True, help_text="Error detail when success=False"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="UTC timestamp of this attempt",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="ContractEvent that triggered this delivery",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_logs",
                        to="ingest.contractevent",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        help_text="Subscription this attempt belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="ingest.webhooksubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["subscription", "timestamp"],
                        name="ingest_webh_subscri_6eca64_idx",
                    )
                ],
            },
        ),
    ]
