# Generated by Django 5.2.10 on 2026-03-27 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0016_trackedcontract_deprecation_fields"),
        ("ingest", "0017_eventdeduplicationlog"),
    ]

    operations = []
